translate chinese strings:
    # game/res/meta/sets.rpym:9
    # game/res/meta/sets.rpym:10
    # game/res/meta/sets.rpym:11
    # game/res/meta/sets.rpym:12
    # game/res/meta/sets.rpym:13
    # game/res/meta/sets.rpym:14
    # game/res/meta/sets.rpym:15
    # game/res/meta/sets.rpym:16
    # game/res/meta/sets.rpym:17
    # game/res/meta/sets.rpym:18
    # game/res/meta/sets.rpym:19
    # game/res/meta/sets.rpym:20
    # game/res/meta/sets.rpym:21
    # game/res/meta/sets.rpym:22
    # game/res/meta/sets.rpym:23
    # game/res/meta/sets.rpym:24
    # game/res/meta/sets.rpym:25
    # game/res/meta/sets.rpym:26
    # game/res/meta/sets.rpym:27
    # game/res/meta/sets.rpym:29
    # game/res/meta/sets.rpym:30
    # game/res/meta/sets.rpym:31
    # game/res/meta/sets.rpym:32
    # game/res/meta/sets.rpym:33
    # game/res/meta/sets.rpym:35
    # game/res/meta/sets.rpym:36
    # game/res/meta/sets.rpym:37
    # game/res/meta/sets.rpym:38
    # game/res/meta/sets.rpym:39
    # game/res/meta/sets.rpym:40
    # game/res/meta/sets.rpym:41
    # game/res/meta/sets.rpym:42
    # game/res/meta/sets.rpym:43
    # game/res/meta/sets.rpym:44
    # game/res/meta/sets.rpym:45
    # game/res/meta/sets.rpym:46
    # game/res/meta/sets.rpym:47
    # game/res/meta/sets.rpym:48
    # game/res/meta/sets.rpym:50
    # game/res/meta/sets.rpym:53
    # game/res/meta/sets.rpym:54
    # game/res/meta/sets.rpym:55
    # game/res/meta/sets.rpym:56
    # game/res/meta/sets.rpym:57
    # game/res/meta/sets.rpym:59
    # game/res/meta/sets.rpym:60
    # game/res/meta/sets.rpym:61
    # game/res/meta/sets.rpym:62
    # game/res/meta/sets.rpym:63
    # game/res/meta/sets.rpym:64
    # game/res/meta/sets.rpym:65
    # game/res/meta/sets.rpym:66
    # game/res/meta/sets.rpym:67
    # game/res/meta/sets.rpym:68
    # game/res/meta/sets.rpym:69
    # game/res/meta/sets.rpym:70
    # game/res/meta/sets.rpym:71
    # game/res/meta/sets.rpym:72
    # game/res/meta/sets.rpym:73
    # game/res/meta/sets.rpym:74
    # game/res/meta/sets.rpym:75
    # game/res/meta/sets.rpym:76
    # game/res/meta/sets.rpym:77
    # game/res/meta/sets.rpym:78
    # game/res/meta/sets.rpym:79
    # game/res/meta/sets.rpym:80
    # game/res/meta/sets.rpym:81
    # game/res/meta/sets.rpym:82
    # game/res/meta/sets.rpym:83
    # game/res/meta/sets.rpym:84
    # game/res/meta/sets.rpym:86
    # game/res/meta/sets.rpym:87
    # game/res/meta/sets.rpym:89
    # game/res/meta/sets.rpym:90
    # game/res/meta/sets.rpym:92
    # game/res/meta/sets.rpym:93
    # game/res/meta/sets.rpym:95
    # game/res/meta/sets.rpym:96
    # game/res/meta/sets.rpym:97
    # game/res/meta/sets.rpym:102
    # game/res/meta/sets.rpym:106
    # game/res/meta/sets.rpym:109
    # game/res/meta/sets.rpym:111
    # game/res/meta/sets.rpym:112
    # game/res/meta/sets.rpym:116
    # game/res/meta/sets.rpym:117
    # game/res/meta/sets.rpym:119
    # game/res/meta/sets.rpym:121
    # game/res/meta/sets.rpym:122
    # game/res/meta/sets.rpym:123
    # game/res/meta/sets.rpym:124
    # game/res/meta/sets.rpym:125
    # game/res/meta/sets.rpym:128
    # game/res/meta/sets.rpym:129
    # game/res/meta/sets.rpym:130
    # game/res/meta/sets.rpym:131
    # game/res/meta/sets.rpym:132
    # game/res/meta/sets.rpym:133
    # game/res/meta/sets.rpym:134
    # game/res/meta/sets.rpym:135
    # game/res/meta/sets.rpym:136
    # game/res/meta/sets.rpym:138
    # game/res/meta/sets.rpym:143
    # game/res/meta/sets.rpym:144
    # game/res/meta/sets.rpym:145
    # game/res/meta/sets.rpym:146
    # game/res/meta/sets.rpym:147
    # game/res/meta/sets.rpym:148
    # game/res/meta/sets.rpym:149
    # game/res/meta/sets.rpym:150
    # game/res/meta/sets.rpym:156
    # game/res/meta/sets.rpym:158
    # game/res/meta/sets.rpym:165
    # game/res/meta/sets.rpym:167
    # game/res/meta/sets.rpym:169
    # game/res/meta/sets.rpym:170
    # game/res/meta/sets.rpym:173
    # game/res/meta/sets.rpym:174
    # game/res/meta/sets.rpym:176
    # game/res/meta/sets.rpym:177
    # game/res/meta/sets.rpym:178
    # game/res/meta/sets.rpym:180
    # game/res/meta/sets.rpym:181
    old "Stairwell"
    new "楼梯间"
    # game/res/meta/sets.rpym:182
    # game/res/meta/sets.rpym:186
    # game/res/meta/sets.rpym:187
    # game/res/meta/sets.rpym:192
    # game/res/meta/sets.rpym:194
    # game/res/meta/sets.rpym:197
    # game/res/meta/sets.rpym:200
    # game/res/meta/sets.rpym:201
    # game/res/meta/sets.rpym:203
    # game/res/meta/sets.rpym:204
    # game/res/meta/sets.rpym:206
    # game/res/meta/sets.rpym:207
    # game/res/meta/sets.rpym:208
    # game/res/meta/sets.rpym:209
    # game/res/meta/sets.rpym:211
    # game/res/meta/sets.rpym:213
    # game/res/meta/sets.rpym:214
    # game/res/meta/sets.rpym:215
    # game/res/meta/sets.rpym:216
    # game/res/meta/sets.rpym:217
    # game/res/meta/sets.rpym:220
    # game/res/meta/sets.rpym:221
    # game/res/meta/sets.rpym:222
    # game/res/meta/sets.rpym:223
    # game/res/meta/sets.rpym:224
    # game/res/meta/sets.rpym:225
    # game/res/meta/sets.rpym:226
    # game/res/meta/sets.rpym:232
    # game/res/meta/sets.rpym:233
    # game/res/meta/sets.rpym:234
    # game/res/meta/sets.rpym:235
    # game/res/meta/sets.rpym:236
    # game/res/meta/sets.rpym:237
    # game/res/meta/sets.rpym:238
    # game/res/meta/sets.rpym:239
    # game/res/meta/sets.rpym:240
    # game/res/meta/sets.rpym:241
    # game/res/meta/sets.rpym:242
    # game/res/meta/sets.rpym:244
    # game/res/meta/sets.rpym:245
    # game/res/meta/sets.rpym:246
    # game/res/meta/sets.rpym:247
    # game/res/meta/sets.rpym:250
    # game/res/meta/sets.rpym:252
    # game/res/meta/sets.rpym:253
    # game/res/meta/sets.rpym:255
    # game/res/meta/sets.rpym:256
    # game/res/meta/sets.rpym:261
    # game/res/meta/sets.rpym:267
    # game/res/meta/sets.rpym:271
    # game/res/meta/sets.rpym:273
    # game/res/meta/sets.rpym:274
    # game/res/meta/sets.rpym:275
    # game/res/meta/sets.rpym:277
    # game/res/meta/sets.rpym:281
    # game/res/meta/sets.rpym:282
    # game/res/meta/sets.rpym:283
    # game/res/meta/sets.rpym:288
    # game/res/meta/sets.rpym:289
    # game/res/meta/sets.rpym:290
    # game/res/meta/sets.rpym:297
    # game/res/meta/sets.rpym:303
    # game/res/meta/sets.rpym:9
    # game/res/meta/sets.rpym:10
    # game/res/meta/sets.rpym:11
    # game/res/meta/sets.rpym:12
    # game/res/meta/sets.rpym:13
    # game/res/meta/sets.rpym:14
    # game/res/meta/sets.rpym:15
    # game/res/meta/sets.rpym:16
    # game/res/meta/sets.rpym:17
    # game/res/meta/sets.rpym:18
    # game/res/meta/sets.rpym:19
    # game/res/meta/sets.rpym:20
    # game/res/meta/sets.rpym:21
    # game/res/meta/sets.rpym:22
    # game/res/meta/sets.rpym:23
    # game/res/meta/sets.rpym:24
    # game/res/meta/sets.rpym:25
    # game/res/meta/sets.rpym:26
    # game/res/meta/sets.rpym:27
    # game/res/meta/sets.rpym:29
    # game/res/meta/sets.rpym:30
    # game/res/meta/sets.rpym:31
    # game/res/meta/sets.rpym:32
    # game/res/meta/sets.rpym:33
    # game/res/meta/sets.rpym:35
    # game/res/meta/sets.rpym:36
    # game/res/meta/sets.rpym:37
    # game/res/meta/sets.rpym:38
    # game/res/meta/sets.rpym:39
    # game/res/meta/sets.rpym:40
    # game/res/meta/sets.rpym:41
    # game/res/meta/sets.rpym:42
    # game/res/meta/sets.rpym:43
    # game/res/meta/sets.rpym:44
    # game/res/meta/sets.rpym:45
    # game/res/meta/sets.rpym:46
    # game/res/meta/sets.rpym:47
    # game/res/meta/sets.rpym:48
    # game/res/meta/sets.rpym:50
    # game/res/meta/sets.rpym:53
    # game/res/meta/sets.rpym:54
    # game/res/meta/sets.rpym:55
    # game/res/meta/sets.rpym:56
    # game/res/meta/sets.rpym:57
    # game/res/meta/sets.rpym:59
    # game/res/meta/sets.rpym:60
    # game/res/meta/sets.rpym:61
    # game/res/meta/sets.rpym:62
    # game/res/meta/sets.rpym:63
    # game/res/meta/sets.rpym:64
    # game/res/meta/sets.rpym:65
    # game/res/meta/sets.rpym:66
    # game/res/meta/sets.rpym:67
    # game/res/meta/sets.rpym:68
    # game/res/meta/sets.rpym:69
    # game/res/meta/sets.rpym:70
    # game/res/meta/sets.rpym:71
    # game/res/meta/sets.rpym:72
    # game/res/meta/sets.rpym:73
    # game/res/meta/sets.rpym:74
    # game/res/meta/sets.rpym:75
    # game/res/meta/sets.rpym:76
    # game/res/meta/sets.rpym:77
    # game/res/meta/sets.rpym:78
    # game/res/meta/sets.rpym:79
    # game/res/meta/sets.rpym:80
    # game/res/meta/sets.rpym:81
    # game/res/meta/sets.rpym:82
    # game/res/meta/sets.rpym:83
    # game/res/meta/sets.rpym:84
    # game/res/meta/sets.rpym:86
    # game/res/meta/sets.rpym:87
    # game/res/meta/sets.rpym:89
    # game/res/meta/sets.rpym:90
    # game/res/meta/sets.rpym:92
    # game/res/meta/sets.rpym:93
    # game/res/meta/sets.rpym:95
    # game/res/meta/sets.rpym:96
    # game/res/meta/sets.rpym:97
    # game/res/meta/sets.rpym:102
    # game/res/meta/sets.rpym:106
    # game/res/meta/sets.rpym:109
    # game/res/meta/sets.rpym:111
    # game/res/meta/sets.rpym:112
    # game/res/meta/sets.rpym:116
    # game/res/meta/sets.rpym:117
    # game/res/meta/sets.rpym:119
    # game/res/meta/sets.rpym:121
    # game/res/meta/sets.rpym:122
    # game/res/meta/sets.rpym:123
    # game/res/meta/sets.rpym:124
    # game/res/meta/sets.rpym:125
    # game/res/meta/sets.rpym:128
    # game/res/meta/sets.rpym:129
    # game/res/meta/sets.rpym:130
    # game/res/meta/sets.rpym:131
    # game/res/meta/sets.rpym:132
    # game/res/meta/sets.rpym:133
    # game/res/meta/sets.rpym:134
    # game/res/meta/sets.rpym:135
    # game/res/meta/sets.rpym:136
    # game/res/meta/sets.rpym:138
    # game/res/meta/sets.rpym:143
    # game/res/meta/sets.rpym:144
    # game/res/meta/sets.rpym:145
    # game/res/meta/sets.rpym:146
    # game/res/meta/sets.rpym:147
    # game/res/meta/sets.rpym:148
    # game/res/meta/sets.rpym:149
    # game/res/meta/sets.rpym:150
    # game/res/meta/sets.rpym:156
    # game/res/meta/sets.rpym:158
    # game/res/meta/sets.rpym:165
    # game/res/meta/sets.rpym:167
    # game/res/meta/sets.rpym:169
    # game/res/meta/sets.rpym:170
    # game/res/meta/sets.rpym:173
    # game/res/meta/sets.rpym:174
    # game/res/meta/sets.rpym:176
    # game/res/meta/sets.rpym:177
    # game/res/meta/sets.rpym:178
    # game/res/meta/sets.rpym:180
    # game/res/meta/sets.rpym:182
    # game/res/meta/sets.rpym:186
    # game/res/meta/sets.rpym:187
    # game/res/meta/sets.rpym:192
    # game/res/meta/sets.rpym:194
    # game/res/meta/sets.rpym:197
    # game/res/meta/sets.rpym:200
    # game/res/meta/sets.rpym:201
    # game/res/meta/sets.rpym:203
    # game/res/meta/sets.rpym:204
    # game/res/meta/sets.rpym:206
    # game/res/meta/sets.rpym:207
    # game/res/meta/sets.rpym:208
    # game/res/meta/sets.rpym:209
    # game/res/meta/sets.rpym:211
    # game/res/meta/sets.rpym:213
    # game/res/meta/sets.rpym:214
    # game/res/meta/sets.rpym:215
    # game/res/meta/sets.rpym:216
    # game/res/meta/sets.rpym:217
    # game/res/meta/sets.rpym:220
    # game/res/meta/sets.rpym:221
    # game/res/meta/sets.rpym:222
    # game/res/meta/sets.rpym:223
    # game/res/meta/sets.rpym:224
    # game/res/meta/sets.rpym:225
    # game/res/meta/sets.rpym:226
    # game/res/meta/sets.rpym:232
    # game/res/meta/sets.rpym:233
    # game/res/meta/sets.rpym:234
    # game/res/meta/sets.rpym:235
    # game/res/meta/sets.rpym:236
    # game/res/meta/sets.rpym:237
    # game/res/meta/sets.rpym:238
    # game/res/meta/sets.rpym:239
    # game/res/meta/sets.rpym:240
    # game/res/meta/sets.rpym:241
    # game/res/meta/sets.rpym:242
    # game/res/meta/sets.rpym:244
    # game/res/meta/sets.rpym:245
    # game/res/meta/sets.rpym:246
    # game/res/meta/sets.rpym:247
    # game/res/meta/sets.rpym:250
    # game/res/meta/sets.rpym:252
    # game/res/meta/sets.rpym:253
    # game/res/meta/sets.rpym:255
    # game/res/meta/sets.rpym:256
    # game/res/meta/sets.rpym:261
    # game/res/meta/sets.rpym:267
    # game/res/meta/sets.rpym:271
    # game/res/meta/sets.rpym:273
    # game/res/meta/sets.rpym:274
    # game/res/meta/sets.rpym:275
    # game/res/meta/sets.rpym:277
    # game/res/meta/sets.rpym:281
    # game/res/meta/sets.rpym:282
    # game/res/meta/sets.rpym:283
    # game/res/meta/sets.rpym:288
    # game/res/meta/sets.rpym:289
    # game/res/meta/sets.rpym:290
    # game/res/meta/sets.rpym:297
    # game/res/meta/sets.rpym:303
